name: YummyAzukibar
version: '${project.version}'
main: com.temps1101.yummyazukibar.yummyazukibar.YummyAzukibar
authors: [ temps1101 ]
description: Plugin to record player's login information
commands:
  logindata:
    aliases: ["ld"]
    permission: yummyazukibar.logindata
permissions:
  yummyazukibar:
    description: Permission to run logindata or not.
    default: op
