name: YummyAzuikibar
version: '${project.version}'
main: com.temps1101.yummyazuikibar.yummyazuikibar.YummyAzuikibar
authors: [ temps1101 ]
description: Plugin to record player's login information
commands:
  logindata:
    aliases: ["ld"]
    permission: yummyazuikibar.logindata
permissions:
  yummyazuikibar:
    description: Permission to run logindata or not.
    default: op
